# Generated by Django 5.1.1 on 2024-09-03 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('produto_id_externo', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='compras/')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('email_cliente', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DetalhesCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.EmailField(max_length=254)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carrinho.compra')),
            ],
        ),
    ]
